# config reference: https://doc.rust-lang.org/cargo/reference/config.html

[target.wasm32-unknown-unknown]
rustflags = ["-C", "target-feature=+atomics,+bulk-memory,+mutable-globals", "-C", "link-arg=--max-memory=4294967296"]

[unstable]
build-std = ["panic_abort", "std"]

[build]
# target required due to `build-std` flag above
# target = "x86_64-unknown-linux-gnu"  # Intel
target = "aarch64-apple-darwin"  # Apple M1
